# Stage 1: Build
FROM node:18-alpine as builder

WORKDIR /app

COPY package.json .
COPY . .
RUN npm install
RUN npm run build

# Stage 2: Production
FROM nginx:1.21.6-alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]